// <auto-generated />
using System;
using Dotabowl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotabowl.Migrations
{
    [DbContext(typeof(DotabowlContext))]
    partial class DotabowlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dotabowl.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ADARGames")
                        .HasColumnType("int");

                    b.Property<int>("ADARLosses")
                        .HasColumnType("int");

                    b.Property<int>("ADARWins")
                        .HasColumnType("int");

                    b.Property<int>("ADGames")
                        .HasColumnType("int");

                    b.Property<int>("ADLosses")
                        .HasColumnType("int");

                    b.Property<int>("ADWins")
                        .HasColumnType("int");

                    b.Property<int>("AllPickGames")
                        .HasColumnType("int");

                    b.Property<int>("AllPickLosses")
                        .HasColumnType("int");

                    b.Property<int>("AllPickWins")
                        .HasColumnType("int");

                    b.Property<int>("AllRandomGames")
                        .HasColumnType("int");

                    b.Property<int>("AllRandomLosses")
                        .HasColumnType("int");

                    b.Property<int>("AllRandomWins")
                        .HasColumnType("int");

                    b.Property<int>("CaptDraftGames")
                        .HasColumnType("int");

                    b.Property<int>("CaptDraftLosses")
                        .HasColumnType("int");

                    b.Property<int>("CaptDraftWins")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RandomDraftGames")
                        .HasColumnType("int");

                    b.Property<int>("RandomDraftLosses")
                        .HasColumnType("int");

                    b.Property<int>("RandomDraftWins")
                        .HasColumnType("int");

                    b.Property<int>("SingleDraftGames")
                        .HasColumnType("int");

                    b.Property<int>("SingleDraftLosses")
                        .HasColumnType("int");

                    b.Property<int>("SingleDraftWins")
                        .HasColumnType("int");

                    b.Property<string>("SteamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalGameTime")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<int>("TurboGames")
                        .HasColumnType("int");

                    b.Property<int>("TurboLosses")
                        .HasColumnType("int");

                    b.Property<int>("TurboWins")
                        .HasColumnType("int");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Mason",
                            ProfilePictureUrl = "assets\\images\\holla.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "hollahataballah",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 4,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Aaron",
                            ProfilePictureUrl = "assets\\images\\aaron.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Grim Strokinoff",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 5,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Alex",
                            ProfilePictureUrl = "assets\\images\\alex.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "TekkPhantom4",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 6,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Arthur",
                            ProfilePictureUrl = "assets\\images\\arthur.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Eddard Slark",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 7,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Beau",
                            ProfilePictureUrl = "assets\\images\\beau.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "rockthecatbox",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 8,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Ben",
                            ProfilePictureUrl = "assets\\images\\ben.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "David Asselhoff",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 9,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Brendan",
                            ProfilePictureUrl = "assets\\images\\brendan.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Rage Factory",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 10,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Donnie",
                            ProfilePictureUrl = "assets\\images\\donnie.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "six",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 11,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Drew",
                            ProfilePictureUrl = "assets\\images\\drew.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Rainmaker",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 12,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Greg",
                            ProfilePictureUrl = "assets\\images\\greg.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "#1BESTDICKSUCKERALIVE",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 13,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Jeff",
                            ProfilePictureUrl = "assets\\images\\jeff.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Actual Waste of Time",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 14,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Lucas",
                            ProfilePictureUrl = "assets\\images\\lucas.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Ham_boy",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 15,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Max",
                            ProfilePictureUrl = "assets\\images\\max.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "ampersand.",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 16,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Sean",
                            ProfilePictureUrl = "assets\\images\\sean.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "SlugmanTheBrave",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 17,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Skyler",
                            ProfilePictureUrl = "assets\\images\\skyler.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Jackal",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 18,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Wes",
                            ProfilePictureUrl = "assets\\images\\wes.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "The Dagon Reborn",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        },
                        new
                        {
                            Id = 19,
                            ADARGames = 0,
                            ADARLosses = 0,
                            ADARWins = 0,
                            ADGames = 0,
                            ADLosses = 0,
                            ADWins = 0,
                            AllPickGames = 0,
                            AllPickLosses = 0,
                            AllPickWins = 0,
                            AllRandomGames = 0,
                            AllRandomLosses = 0,
                            AllRandomWins = 0,
                            CaptDraftGames = 0,
                            CaptDraftLosses = 0,
                            CaptDraftWins = 0,
                            Name = "Vincent",
                            ProfilePictureUrl = "assets\\images\\zoltrix.jpg",
                            RandomDraftGames = 0,
                            RandomDraftLosses = 0,
                            RandomDraftWins = 0,
                            SingleDraftGames = 0,
                            SingleDraftLosses = 0,
                            SingleDraftWins = 0,
                            SteamName = "Zoltrix",
                            TotalGameTime = 0m,
                            TotalGames = 0,
                            TotalLosses = 0,
                            TotalWins = 0,
                            TurboGames = 0,
                            TurboLosses = 0,
                            TurboWins = 0,
                            WinRate = 0m
                        });
                });

            modelBuilder.Entity("Dotabowl.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DireKills")
                        .HasColumnType("int");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadiantKills")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MatchParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("MatchParticipant", b =>
                {
                    b.HasOne("Dotabowl.Data.Models.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotabowl.Api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dotabowl.Data.Models.Match", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
